# Generated by Django 3.0 on 2019-12-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_river', models.DecimalField(decimal_places=4, max_digits=20)),
                ('road_access', models.CharField(max_length=100)),
                ('distance_from_main_city', models.DecimalField(decimal_places=4, max_digits=20)),
                ('slope', models.CharField(max_length=100)),
                ('direct_distance_from_forest', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_voltage_transmisison_line', models.CharField(max_length=100)),
                ('flood_risk_level', models.DecimalField(decimal_places=4, max_digits=20)),
                ('land_slide_risk', models.DecimalField(decimal_places=4, max_digits=20)),
                ('elevation', models.DecimalField(decimal_places=4, max_digits=20)),
                ('land_type', models.CharField(max_length=100)),
                ('land_use', models.CharField(max_length=100)),
            ],
        ),
    ]
